/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-dim":                "#131313",
        "inverse-primary":            "#5d5f5f",
        "outline-variant":            "#444748",
        "on-tertiary-fixed":          "#1a1c19",
        "tertiary-fixed-dim":         "#c6c7c2",
        "on-secondary":               "#3c2f00",
        "inverse-on-surface":         "#313030",
        "surface-container-highest":  "#353535",
        "background":                 "#131313",
        "on-tertiary-fixed-variant":  "#454744",
        "surface-bright":             "#393939",
        "on-secondary-fixed-variant": "#574500",
        "error-container":            "#93000a",
        "surface-container-high":     "#2a2a2a",
        "inverse-surface":            "#e5e2e1",
        "on-secondary-container":     "#342800",
        "on-primary":                 "#2f3131",
        "surface-tint":               "#c6c6c7",
        "surface-container-lowest":   "#0e0e0e",
        "on-primary-fixed-variant":   "#454747",
        "secondary":                  "#e9c349",
        "primary-fixed":              "#e2e2e2",
        "surface-container-low":      "#1b1b1b",
        "primary-container":          "#e2e2e2",
        "surface-container":          "#20201f",
        "on-error":                   "#690005",
        "outline":                    "#8e9192",
        "on-tertiary-container":      "#636561",
        "on-tertiary":                "#2f312e",
        "surface":                    "#131313",
        "primary-fixed-dim":          "#c6c6c7",
        "secondary-container":        "#af8d11",
        "tertiary":                   "#ffffff",
        "tertiary-fixed":             "#e3e3de",
        "on-primary-fixed":           "#1a1c1c",
        "on-background":              "#e5e2e1",
        "surface-variant":            "#353535",
        "on-surface-variant":         "#c4c7c8",
        "on-surface":                 "#e5e2e1",
        "on-error-container":         "#ffdad6",
        "on-secondary-fixed":         "#241a00",
        "on-primary-container":       "#636565",
        "error":                      "#ffb4ab",
        "primary":                    "#ffffff",
        "tertiary-container":         "#e3e3de",
        "secondary-fixed-dim":        "#e9c349",
        "secondary-fixed":            "#ffe088",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg:      "0.5rem",
        xl:      "0.75rem",
        full:    "9999px",
      },
      spacing: {
        "container-max": "1440px",
        "stack-md":      "4rem",
        "stack-lg":      "8rem",
        "stack-sm":      "2rem",
        "margin-x":      "4rem",
        "gutter":        "2rem",
      },
      fontFamily: {
        "label-sm":          ["Manrope", "sans-serif"],
        "headline-sm":       ["Playfair Display", "serif"],
        "headline-md":       ["Playfair Display", "serif"],
        "display-lg":        ["Playfair Display", "serif"],
        "display-lg-mobile": ["Playfair Display", "serif"],
        "body-md":           ["Manrope", "sans-serif"],
        "body-lg":           ["Manrope", "sans-serif"],
      },
      fontSize: {
        "label-sm":          ["12px",  { lineHeight: "1",   letterSpacing: "0.1em",   fontWeight: "600" }],
        "headline-sm":       ["24px",  { lineHeight: "1.4",                            fontWeight: "400" }],
        "headline-md":       ["32px",  { lineHeight: "1.3",                            fontWeight: "400" }],
        "display-lg":        ["64px",  { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "400" }],
        "display-lg-mobile": ["40px",  { lineHeight: "1.2",                            fontWeight: "400" }],
        "body-md":           ["16px",  { lineHeight: "1.6",                            fontWeight: "400" }],
        "body-lg":           ["18px",  { lineHeight: "1.6", letterSpacing: "0.01em",  fontWeight: "300" }],
      },
      maxWidth: {
        "container-max": "1440px",
      },
    },
  },
  plugins: [],
}

